apiVersion: v1
kind: ServiceAccount
metadata:
  name: spekt8
  namespace: poc-bruno
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: fabric8-rbac
subjects:
 - kind: ServiceAccount
   name: spekt8
   #namespace: default
   namespace: poc-bruno
roleRef:
 kind: ClusterRole
 name: cluster-admin
 apiGroup: rbac.authorization.k8s.io
