apiVersion: v1
kind: Service
metadata:
  name: spekt8
  namespace: poc-bruno
spec:
  type: NodePort
  selector:
    component: spekt8
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30432
 
